### ISSUE TITLE
Error `Route with similar path already exists`

### ISSUE THREAD

**Issue by desugar-64** [hokolinks/hoko-android#14]
Hi. I am trying to map my route but constantly getting the error:

``` java
Hoko.deeplinking().mapRoute("sharedauction?auid=:auid&bid=:bid", new DeeplinkCallback() {
            @Override
            public void deeplinkOpened(Deeplink deeplink) {
            }
 });
```

``` json
{
"error":"Could not save route 'sharedauction?auid=:auid&bid=:bid': Route with similar path already exists","status":8
}
```

But on hoko's dashboard I can't find this route in templates menu. ![templates1](https://sc-cdn.scaleengine.net/i/769f2ff3e3201d2d2bc1c289b1d53377.png)
Available paths for this route.
![templates2](https://sc-cdn.scaleengine.net/i/bf4a3732949a8fb63c92bf995ef0f467.png)

**Comment by hugocore** [comment]
Hi @sergeyfitis,

We realise that that the error message is not the best one. Therefore we changed the message error to something a bit more descriptive. In your case the error message now is:

```
Route has the same static URL and similar variables as: '1167 : /sharedauction'
```

The problem is that you already have a route with the URL "/sharedauction". Since you are using query parameters and those can be optional, we interpret this route as being the same as the one you are trying to create.

If you want we can replace that route path to the one you are trying to create and use it in your template.

**Comment by desugar-64** [comment]
> If you want we can replace that route path to the one you are trying to create and use it in your template.

Thanks. That would be great.

**Comment by desugar-64** [comment]
@hugocore But why it is possible to create the route on ios? 
![image](https://sc-cdn.scaleengine.net/i/a6c0438bfc0e8128e1d99fa3207e16a2.png)

/sharedauction in two instances

**Comment by desugar-64** [comment]
@hugocore The route is available now. Thank you very much 
![img](https://sc-cdn.scaleengine.net/i/8a657523f04103b59bd3f9f56acd5e29.png)

**Comment by hugocore** [comment]
I just added the route now. Take a look.

Your templates seem to be using the right routes now.

There was a lot of garbage routes in there.

**Comment by desugar-64** [comment]
@hugocore Buy the way. Is it possible to remove unsed routs by myself? Some SDK APIs maybe?

**Comment by hugocore** [comment]
We are working on ways to make that happen. In the meantime we have to manually delete them for you.
