### ISSUE TITLE
@DeeplinkFragmentActivity and android:launchMode="singleTop"

### ISSUE THREAD

**Issue by enterpredator** [hokolinks/hoko-android#9]
I have FragmentActivity showing various fragments (depend on smartlink route).
This Activity marked by **@DeeplinkFragmentActivity**(id = R.id.content_frame, fragments = { ... }) and it also contains **android:launchMode="singleTop"** attribute in the manifest, for handle Intent.ACTION_SEARCH in [onNewIntent(Intent)](http://developer.android.com/intl/ru/reference/android/app/Activity.html#onNewIntent%28android.content.Intent%29) method.
In this way, when clicking on the smartlink for the first time the Activity starting and showing a fragment.
But if we collapse application (not close) and click on the smartlink again the Activity just back to foreground and not instantiate any fragment, because in this case [onNewIntent(Intent)](http://developer.android.com/intl/ru/reference/android/app/Activity.html#onNewIntent%28android.content.Intent%29) method will be called and our [Activity will not re-create](http://developer.android.com/intl/ru/guide/topics/manifest/activity-element.html).

> Launch Mode "singleTop"
> If an instance of the activity already exists at the top of the target task, the system routes the intent to that instance through a call to its onNewIntent() method, rather than creating a new instance of the activity.

How can we handle this situation?
Maybe we can use Hoko.deeplinking().inject forced for instantiate right fragment in onNewIntent(Intent) method of our Activity?

**Comment by ivanbruel** [comment]
That sounds about right. The only issue I see there is that you need to call `setIntent(newIntent)` on the `onNewIntent(Intent)` method because `Hoko.deeplinking().inject(Activity)` uses the `getIntent()` to get the serialized deeplinking data.

``` java
protected void onNewIntent(Intent newIntent) {
  // your search logic
  // ...
 setIntent(newIntent);
 if (Hoko.deeplinking.inject(this)) {
   // Hoko injected
 }
}
```

I will keep this issue opened as it might make sense to add a new `Hoko.deeplinking().inject(Activity, Intent)` method overloading to make sure this case is covered without the caveat of having to call `setIntent(Intent)` beforehand.
